export const keywordsForMetaData: Array<string> = [
  "FileFlash platform",
  "Peer-to-peer file transfer",
  "Real-time file sharing",
  "Efficient file transfer",
  "P2P data exchange",
  "Secure file sharing technology",
  "WebRTC-based file sharing",
  "Next.js application",
  "TypeScript-based file transfer",
  "Rapid data transfer",
  "Instant file messaging",
  "Direct peer-to-peer communication",
  "High-speed and secure file sharing",
  "Optimized file exchange",
  "Web-based file sharing solution",
  "Next.js with TypeScript integration",
  "Ultra-fast file transfer",
  "File sharing with chat capabilities",
  "FileFlash web interface",
  "Seamless file transfer experience",
  "Swift file exchange",
  "Effortless P2P connectivity",
  "Robust file transfer security",
  "Intuitive file sharing interface",
  "Live file exchange",
  "Next.js development expertise",
  "Web app creation",
  "Unique FileFlash features",
  "File sharing service",
  "Secure communication and file sharing",
  "Collaborative P2P file sharing",
  "Effective data transfer solutions",
  "Next.js TypeScript integration",
  "Contemporary file sharing methods",
  "Reliable file exchange",
  "WebRTC-enabled chat and file sharing",
  "Next.js development expertise",
  "P2P file transfer solutions",
  "Advantages of FileFlash",
];
